name: Push
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pushed"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
